---
title: "COVID-19 in Canada (as of `r Sys.time()`)"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
orientation: columns
vertical_layout: fill
---
  

```{r setup, include=FALSE}
require(tidyverse)
require(plotly)
require(lubridate)

covid <- read.csv("https://health-infobase.canada.ca/src/data/covidLive/covid19-download.csv")


head(covid)
ns <- covid[!covid$prname=="Canada",]

```


Charts
=======================================================================

Column 
-----------------------------------------------------------------------

### Positive test rate

```{r}
ggplotly(ggplot() + geom_point(data=ns, aes(ymd(date), percentoday, colour=prname)) + geom_line(data=ns, aes(ymd(date), percentoday, colour=prname, group=prname)) +
 ylab("Percentage of tests positive") +
           xlab("Date"))
```

### Daily case count

```{r}
ggplotly(ggplot() + geom_point(data=ns, aes(ymd(date), numtoday, colour=prname)) + geom_line(data=ns, aes(ymd(date), numtoday, colour=prname, group=prname)) +
           ylab("Number of cases") +
           xlab("Date"))

```


Column 
-----------------------------------------------------------------------

### Testing 

```{r}
ggplotly(ggplot() + geom_point(data=ns, aes(ymd(date), numtestedtoday, colour=prname)) + geom_line(data=ns, aes(ymd(date), numtestedtoday, group=prname, colour=prname)) +
           ylab("Number of tests") +
           xlab("Date"))
```


### Cumulative case count (aka. "THE CURVE")

```{r}
ggplotly(ggplot() + geom_point(data=ns, aes(ymd(date), numtotal, colour=prname)) + geom_line(data=ns, aes(ymd(date), numtotal, colour=prname)) +
           ylab("Cumulative cases") +
           xlab("Date"))
```




Table
========================================================================

Column {data-width=400}
-------------------------------------------------------------------------

### Monthly stats

```{r, echo=F}
table <- ns %>%
  mutate(month=month(ymd(date)),
         year=year(ymd(date)))%>%
  group_by(prname, year, month) %>%
  summarize(cases_per_day = mean(numtoday),
            median_cases = median(numtoday),
            total_cases = sum(numtoday))
knitr::kable(table)
```